routes/admin.php
<?php
Auth::routes();

Route::resource('movie', 'MovieController');

Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);

Route::post('movie/show', ['as' => 'movie/show', 'uses' => 'MovieController@show']);
Route::resource('user', 'UserController');

Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);

Route::post('user/show', ['as' => 'user/show', 'uses' => 'UserController@show']);

//Categories
Route::resource('categorie', 'CategorieController');
Route::get('categorie/destroy/{id}', ['as' => 'categorie/destroy', 'uses' => 'CategorieController@destroy']);
Route::post('categorie/show', ['as' => 'categorie/show', 'uses' => 'CategorieController@show']);
Route::post('categorie/show', ['as' => 'categorie/store', 'uses' => 'CategorieController@store']);
Route::post('categorie/show', ['as' => 'categorie/update', 'uses' => 'CategorieController@update']);

routes/user.php
<?php
//Movie
Auth::routes();
Route::get('user/movie', ['as' => 'user/movie', 'uses' => 'MovieController@index']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Otros
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




//Route::resource('states', 'StatesController');



//Route::post('state/show', ['as' => 'state/show', 'uses' => 'StatesController@show']);
//Categorie Movie
/*Route::resource('categorie_movie', 'Categorie_MovieController');

Route::post('categorie_movie/show', ['as' => 'categorie_movie/show', 'uses' => 'Categorie_MovieController@show']);

Route::get('categorie_movie/destroy/{id}', ['as' => 'categorie_movie/destroy', 'uses' => 'Categorie_MovieController@destroy']);*/

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">   
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'movie/show', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('user.index') }}" class="btn btn-success">Usuarios</a>
						<a href="{{ route('categorie.index') }}" class="btn btn-success">Categorías</a>
						<a href="{{ route('categorie_movie.index') }}" class="btn btn-success">Peliculas con categoria</a>
						<a href="{{ route('movie.index') }}" class="btn btn-primary">Todos</a>
						<a href="{{ route('movie.create') }}" class="btn btn-primary">Crear</a>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Descripción</th>
							<th>Usuario</th>
							<th>State</th>
							<th>Fecha de creación</th>
							<th>Fecha de actualización</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($movies as $movie)
							<tr>
								<td>{{ $movie->name }}</td>
								<td>{{ $movie->description }}</td>
								<td>{{ $movie->user_id }}</td>
								<td>{{ $movie->state_id }}</td>
								<td>{{ $movie->created_at }}</td>
								<td>{{ $movie->updated_at }}</td>
								<td>
							@if ($show_edit_delete)

									<a href="{{ route('movie.edit', ['id' => $movie->id]) }}" class="btn btn-primary btn-xs">Editar</a>
									<a href="{{ route('movie/destroy',['id' => $movie->id]) }}" class="btn btn-danger btn-xs">Borrar</a>
									 @endif 
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/movies/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'movie.store', 'method' => 'post', 'novalidate']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<input type="text" name="description" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Usuario</label>
						<select class="form-control" name="user_id"> 
							@foreach($users as $user)
								<option  value="{{ $user->id}}">{{ $user->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Estado</label>
						<select class="form-control" name="state_id">
							@foreach($states as $state)
								<option  value="{{ $state->id}}">{{ $state->state }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($movie, ['route' => ['movie.update', $movie->id], 'method' => 'put']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required value="{{ $movie->name }}">
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<input type="text" name="description" class="form-control" required value="{{ $movie->description }}">
					</div>
					<div class="form-group">
						<label>Usuario</label>
						<select class="form-group" name="user_id"> 
							@foreach($users as $user)
								<option  value="{{ $user->id}}">{{ $user->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Estado</label>
						<select class="form-control" name="state_id">
							@foreach($states as $state)
								<option  value="{{$state->id}}">{{ $state->state }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection