routes/admin.php
<?php
Auth::routes();

Route::resource('movie', 'MovieController');

Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);

Route::post('movie/show', ['as' => 'movie/show', 'uses' => 'MovieController@show']);
Route::resource('user', 'UserController');

Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);

Route::post('user/show', ['as' => 'user/show', 'uses' => 'UserController@show']);

//Categories
Route::resource('categorie', 'CategorieController');
Route::get('categorie/destroy/{id}', ['as' => 'categorie/destroy', 'uses' => 'CategorieController@destroy']);
Route::post('categorie/show', ['as' => 'categorie/show', 'uses' => 'CategorieController@show']);
Route::post('categorie/show', ['as' => 'categorie/store', 'uses' => 'CategorieController@store']);
Route::post('categorie/show', ['as' => 'categorie/update', 'uses' => 'CategorieController@update']);

routes/user.php
<?php
//Movie
Auth::routes();
Route::get('user/movie', ['as' => 'user/movie', 'uses' => 'MovieController@index']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Otros
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




//Route::resource('states', 'StatesController');



//Route::post('state/show', ['as' => 'state/show', 'uses' => 'StatesController@show']);
//Categorie Movie
/*Route::resource('categorie_movie', 'Categorie_MovieController');

Route::post('categorie_movie/show', ['as' => 'categorie_movie/show', 'uses' => 'Categorie_MovieController@show']);

Route::get('categorie_movie/destroy/{id}', ['as' => 'categorie_movie/destroy', 'uses' => 'Categorie_MovieController@destroy']);*/

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable; 

class User extends  Authenticatable
{
	
    protected $table = 'users';
    protected $fillable = ['name', 'email', 'password', 'state_id','role'];
    protected $guarded = ['id'];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User as User;
use App\Models\State as State;

class UserController extends Controller
{
	public function destroy($id)
	{
		$user = User::find($id);
		$user->delete();
		return redirect()->back();
	}

	public function show (Request $request)
	{
		$users = User::where('name', 'like', '%'.$request->name.'%')->get();
		return \View::make('users/list', compact('users'));
	}

	public function update($id, Request $request)
	{
		$user = User::find($id);
		$user->name = $request->name;
		$user->email = $request->email;
		$user->password = $request->password;
		$user->state_id = $request->state_id;
		$user->save();
		return redirect('user');
	}

	public function edit($id)
	{
		$user = User::find($id);
		$states = State::all();
		return \View::make('users/update', compact('user', 'states'));
	}

    public function index()
    {
    	$users = User::all();
    	return \View::make('users/list', compact('users'));
    }

    public function create()
    {
    	$states = State::all();
    	return \View::make('users/new', compact('states'));
    }

    public function store(Request $request)
    {
    	$user = new User;
    	$user->name = $request->name;
    	$user->email = $request->email;
    	$user->password = $request->password;
    	$user->state_id = $request->state_id;
    	return redirect('user');
    }
}

resources/views/users/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'user/show', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('movie.index') }}" class="btn btn-success">Peliculas</a>
						<a href="{{ route('categorie.index') }}" class="btn btn-success">Categorías</a>
						<a href="{{ route('categorie_movie.index') }}" class="btn btn-success">Peliculas con categoria</a>
						<a href="{{ route('user.index') }}" class="btn btn-primary">Todos</a>
						<a href="{{ route('user.create') }}" class="btn btn-primary">Crear</a>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-striped table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Email</th>
							<th>Contraseña</th>
							<th>Estado</th>
							<th>Fecha de creación</th>
							<th>Fecha de actualización</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($users as $user)
							<tr>
								<td>{{ $user->name }}</td>
								<td>{{ $user->email }}</td>
								<td>{{ $user->password }}</td>
								<td>{{ $user->state_id }}</td>
								<td>{{ $user->created_at }}</td>
								<td>{{ $user->updated_at }}</td>
								<td>
									<a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-primary btn-xs">Editar</a>
									<a href="{{ route('user/destroy', ['id' => $user->id]) }}" class="btn btn-danger btn-xs">Borrar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/users/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'user.store', 'method' => 'post', 'novalidate']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Contraseña</label>
						<input type="password" name="password" class="form-control" required>
					</div>
					<div class="form-group"> 
						<label>Estado</label>
						<select name="state_id" class="form-control">
							@foreach($states as $state)
								<option value="{{ $state->id }}">{{ $state->state }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/users/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put']) !!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control" value="{{$user->name}}" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" required value="{{ $user->email}}">
					</div>
					<div class="form-group">
						<label>Contraseña</label>
						<input type="password" name="password" class="form-control" required value="{{$user->password}}">
					</div>
					<div class="form-group">
						<label>Estado</label>
						<select name="state_id" class="form-control">
							@foreach($states as $state)
								<option value="{{ $state->id }}">{{ $state->state }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection