routes/admin.php
<?php
Auth::routes();

Route::resource('movie', 'MovieController');

Route::get('movie/destroy/{id}', ['as' => 'movie/destroy', 'uses' => 'MovieController@destroy']);

Route::post('movie/show', ['as' => 'movie/show', 'uses' => 'MovieController@show']);
Route::resource('user', 'UserController');

Route::get('user/destroy/{id}', ['as' => 'user/destroy', 'uses' => 'UserController@destroy']);

Route::post('user/show', ['as' => 'user/show', 'uses' => 'UserController@show']);

//Categories
Route::resource('categorie', 'CategorieController');
Route::get('categorie/destroy/{id}', ['as' => 'categorie/destroy', 'uses' => 'CategorieController@destroy']);
Route::post('categorie/show', ['as' => 'categorie/show', 'uses' => 'CategorieController@show']);
Route::post('categorie/show', ['as' => 'categorie/store', 'uses' => 'CategorieController@store']);
Route::post('categorie/show', ['as' => 'categorie/update', 'uses' => 'CategorieController@update']);

routes/user.php
<?php
//Movie
Auth::routes();
Route::get('user/movie', ['as' => 'user/movie', 'uses' => 'MovieController@index']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Otros
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');




//Route::resource('states', 'StatesController');



//Route::post('state/show', ['as' => 'state/show', 'uses' => 'StatesController@show']);
//Categorie Movie
/*Route::resource('categorie_movie', 'Categorie_MovieController');

Route::post('categorie_movie/show', ['as' => 'categorie_movie/show', 'uses' => 'Categorie_MovieController@show']);

Route::get('categorie_movie/destroy/{id}', ['as' => 'categorie_movie/destroy', 'uses' => 'Categorie_MovieController@destroy']);*/

resources/views/categories_movies/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!! Form::open(['route' => 'categorie_movie/show', 'method' => 'post', 'novalidate', 'class' => 'form-inline']) !!}
					<div class="form-group">
						<label>Nombre pelicula</label>
						<input type="text" name="name" class="form-control">
					</div>
					<div class="form-control">
						<button type="submit" class="btn btn-default">Buscar</button>
						<a href="{{ route('user.index') }}" class="btn btn-success">Usuarios</a>
						<a href="{{ route('movie.index') }}" class="btn btn-success">Peliculas</a>
						<a href="{{ route('categorie.index') }}" class="btn btn-success">Categorías</a>
						<a href="{{ route('categorie_movie.index') }}" class="btn btn-primary">Todos</a>
						<a href="{{ route('categorie_movie.create') }}" class="btn btn-primary">Crear</a>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-striped table-condensed table-bordered">
					<thead>
						<tr>
							<th>Pelicula</th>
							<th>Categoría</th>
							<th>Estado</th>
							<th>Fecha de creación</th>
							<th>Fecha de actualización</th>
							<th>Acción</th>
						</tr>
					</thead>
					<tbody>
						@foreach($categories_movies as $categorie_movie)
							<tr>
								<td>{{ $categorie_movie->movie_id }}</td>
								<td>{{ $categorie_movie->category_id }}</td>
								<td>{{ $categorie_movie->state_id }}</td>
								<td>{{ $categorie_movie->created_at }}</td>
								<td>{{ $categorie_movie->updated_at }}</td>
								<td>
									<a href="{{ route('categorie_movie.edit', ['id' => $categorie_movie->id]) }}" class="btn btn-primary">Editar</a>
									<a href="{{ route('categorie_movie/destroy', ['id' => $categorie_movie->id ]) }}" class="btn btn-danger">Borrar</a>
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/categories_movies/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::open(['route' => 'categorie_movie.store', 'method' => 'post', 'novalidate']) !!}
					<div class="form-group">
						<label>Película</label>
						<select name="movie_id" class="form-control">
							@foreach($movies as $movie)
								<option value="{{$movie->id}}">{{$movie->name}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Categoría</label>
						<select name="category_id" class="form-control">
							@foreach($categories as $categorie)
								<option value="{{$categorie->id}}">{{$categorie->name}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Estado</label>
						<select name="state_id" class="form-control">
							@foreach($states as $state)
								<option value="{{$state->id}}">{{$state->state}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button class="btn btn-success" type="submit">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>
	</section>
@endsection

resources/views/categories_movies/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!! Form::model($categorie_movie, ['route' => ['categorie_movie.update', $categorie_movie->id], 'method' => 'put']) !!}
					<div class="form-group">
						<label>Pelicula</label>	
						<select name="movie_id" class="form-control">
							@foreach($movies as $movie)
								<option value="{{ $movie->id }}">{{ $movie->name }}</option>
							@endforeach
						</select>					
					</div>
					<div class="form-group">
						<label>Categoría</label>
						<select name="category_id" class="form-control">
							@foreach($categories as $categorie)
								<option value="{{ $categorie->id }}">{{ $categorie->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Estado</label>
						<select name="state_id" class="form-control">
							@foreach($states as $state)
								<option value="{{ $state->id }}">{{$state->state}}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Enviar</button>
					</div>
				{!! Form::close() !!}
			</article>
		</div>	   
	</section>
@endsection